# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

# Adapter settings for postgresql

#development:
#  adapter: postgresql
#  encoding: unicode
#  database: ace_app_development
#  pool: 5
#  username: ace_app_user
#  password:

# Adapter settings for mysql
development:
  adapter: mysql2
  encoding: utf8
  database: ace_app_development
  username: ace_app_user
  password: robots
#  host: localhost
#  port: 3000

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

# Adapter settings for postgresql

#test:
#  adapter: postgresql
#  encoding: unicode
#  database: ace_app_test
#  pool: 5
#  username: ace_app_user
#  password:

# Adapter settings for mysql
test:
  adapter: mysql2
  encoding: ut8
  database: ace_app_test
  username: ace_app_user
  password: robots
#  host: localhost
#  port: 3000



# Adapter settings for postgresql

#production:
#  adapter: postgresql
#  encoding: unicode
#  database: ace_app_production
#  pool: 5
#  username: ace_app_user
#  password:

# Adapter settings for mysql
production:
  adapter: mysql2
  encoding: utf8
  database: ace_app_test
  username: ace_app_user
  password: robots
  host: localhost
  port: 80